# Generated by Django 4.2.3 on 2023-11-20 04:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectogymflow', '0005_remove_perfil_nombre_remove_user_list_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perfil',
            new_name='perfil_usuario_login',
        ),
    ]
